module.exports = {
  future: {
    // removeDeprecatedGapUtilities: true,
    // purgeLayersByDefault: true,
  },
  purge: [],
  theme: {
    screens: {
      sm: '360px',
      md: '768px',
      lg: '1140px',
      xl: '1440px',
    },
    extend: {
      colors: {
        'page-primary': '#F9FAFC',
        'modal-primary': '#FFF',
        'lines-primary': '#ECF0F4',
        'lines-secondary': '#2B3A5B',
        'font-primary': '#161E2E',
        'font-secondary': '#9EA4B8',
        'font-tertiary': '#ADADAD',
        'font-quaternary': '#6B7280',
        'primary-orange': '#FFDC97',
        'primary-green': '#36C44D',
        'primary-red': '#FE3653',
        'primary-purple': '#8F5EE1',
        'primary-blue': '#386EF7',
        'primary-blue-hover': '#6691FF',
        'primary-blue-pressed': '#335ECC',
        'primary-info': '#F4F7FF',
        'avatar-primary': '#EDF0F5',
        'secondary-purple': '#ECE9FF',
        'tertiary-blue': '#ECF1FF',
        'secondary-blue': '#6E96FB',
        'secondary-blue-hover': '#F2F6FF',
        'secondary-green': '#EFFBF1',
        'secondary-red': '#FBB9C4',
        'secondary-orange': '#FFF8E8',
        'disabled-gray': '#ECEFF4',
        'gray-50': '#F3F3F3',
      },
      minHeight: {
        6: '1.5rem',
      },
      maxWidth: {
        '4xs': '8rem',
      },
      lineHeight: {
        20: '5rem',
        16: '4rem',
      },
      fontFamily: {
        sans: [
          'Montserrat',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'Noto Sans',
          'sans-serif',
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol',
          'Noto Color Emoji',
        ],
      },
    },
  },
  variants: {
    boxShadow: ['responsive', 'hover', 'focus', 'active'],
  },
}
